# Generated by Django 3.2.8 on 2022-11-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hash', models.CharField(max_length=66)),
                ('parent_hash', models.CharField(max_length=66)),
                ('nonce', models.CharField(max_length=66)),
                ('sha3_uncles', models.CharField(max_length=66)),
                ('logs_bloom', models.CharField(max_length=512)),
                ('transactions_root', models.CharField(max_length=66)),
                ('state_root', models.CharField(max_length=66)),
                ('receipts_root', models.CharField(max_length=66)),
                ('miner', models.CharField(max_length=42)),
                ('difficulty', models.IntegerField()),
                ('total_difficulty', models.IntegerField()),
                ('size', models.IntegerField()),
                ('extra_data', models.CharField(max_length=66)),
                ('gas_limit', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('uncles', models.CharField(max_length=66)),
            ],
        ),
    ]
